/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileSlugRouteImport } from './routes/profile.$slug'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBookingRouteImport } from './routes/_authenticated/booking'
import { Route as AuthenticatedDashboardProfessionalRouteImport } from './routes/_authenticated/dashboard.professional'
import { Route as AuthenticatedDashboardClientRouteImport } from './routes/_authenticated/dashboard.client'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSlugRoute = ProfileSlugRouteImport.update({
  id: '/profile/$slug',
  path: '/profile/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingRoute = AuthenticatedBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardProfessionalRoute =
  AuthenticatedDashboardProfessionalRouteImport.update({
    id: '/dashboard/professional',
    path: '/dashboard/professional',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardClientRoute =
  AuthenticatedDashboardClientRouteImport.update({
    id: '/dashboard/client',
    path: '/dashboard/client',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/client': typeof AuthenticatedDashboardClientRoute
  '/dashboard/professional': typeof AuthenticatedDashboardProfessionalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/client': typeof AuthenticatedDashboardClientRoute
  '/dashboard/professional': typeof AuthenticatedDashboardProfessionalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/search': typeof SearchRoute
  '/_authenticated/booking': typeof AuthenticatedBookingRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/client': typeof AuthenticatedDashboardClientRoute
  '/_authenticated/dashboard/professional': typeof AuthenticatedDashboardProfessionalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/booking'
    | '/chat'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/profile/$slug'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/professional'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/booking'
    | '/chat'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/profile/$slug'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/professional'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/search'
    | '/_authenticated/booking'
    | '/_authenticated/chat'
    | '/_authenticated/settings'
    | '/auth/login'
    | '/auth/register'
    | '/profile/$slug'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/client'
    | '/_authenticated/dashboard/professional'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SearchRoute: typeof SearchRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProfileSlugRoute: typeof ProfileSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$slug': {
      id: '/profile/$slug'
      path: '/profile/$slug'
      fullPath: '/profile/$slug'
      preLoaderRoute: typeof ProfileSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/booking': {
      id: '/_authenticated/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof AuthenticatedBookingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/professional': {
      id: '/_authenticated/dashboard/professional'
      path: '/dashboard/professional'
      fullPath: '/dashboard/professional'
      preLoaderRoute: typeof AuthenticatedDashboardProfessionalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/client': {
      id: '/_authenticated/dashboard/client'
      path: '/dashboard/client'
      fullPath: '/dashboard/client'
      preLoaderRoute: typeof AuthenticatedDashboardClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBookingRoute: typeof AuthenticatedBookingRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardClientRoute: typeof AuthenticatedDashboardClientRoute
  AuthenticatedDashboardProfessionalRoute: typeof AuthenticatedDashboardProfessionalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookingRoute: AuthenticatedBookingRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
  AuthenticatedDashboardClientRoute: AuthenticatedDashboardClientRoute,
  AuthenticatedDashboardProfessionalRoute:
    AuthenticatedDashboardProfessionalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SearchRoute: SearchRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProfileSlugRoute: ProfileSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
