/* eslint-disable */
// This file is auto-generated by TanStack Router
// Do not edit this file manually

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as SearchRoute } from './routes/search'
import { Route as AuthLoginRoute } from './routes/auth.login'
import { Route as AuthRegisterRoute } from './routes/auth.register'
import { Route as ProfileSlugRoute } from './routes/profile.$slug'
import { Route as AuthenticatedRoute } from './routes/_authenticated'
import { Route as AuthenticatedChatRoute } from './routes/_authenticated/chat'
import { Route as AuthenticatedBookingRoute } from './routes/_authenticated/booking'
import { Route as AuthenticatedDashboardClientRoute } from './routes/_authenticated/dashboard.client'
import { Route as AuthenticatedDashboardProfessionalRoute } from './routes/_authenticated/dashboard.professional'
import { Route as AuthenticatedDashboardAdminRoute } from './routes/_authenticated/dashboard.admin'

const rootRouteWithChildren = rootRoute.addChildren([
  IndexRoute,
  SearchRoute,
  AuthLoginRoute,
  AuthRegisterRoute,
  ProfileSlugRoute,
  AuthenticatedRoute.addChildren([
    AuthenticatedChatRoute,
    AuthenticatedBookingRoute,
    AuthenticatedDashboardClientRoute,
    AuthenticatedDashboardProfessionalRoute,
    AuthenticatedDashboardAdminRoute,
  ]),
])

export const routeTree = rootRouteWithChildren

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { preLoaderRoute: typeof IndexRoute; parentRoute: typeof rootRoute }
    '/search': { preLoaderRoute: typeof SearchRoute; parentRoute: typeof rootRoute }
    '/auth/login': { preLoaderRoute: typeof AuthLoginRoute; parentRoute: typeof rootRoute }
    '/auth/register': { preLoaderRoute: typeof AuthRegisterRoute; parentRoute: typeof rootRoute }
    '/profile/$slug': { preLoaderRoute: typeof ProfileSlugRoute; parentRoute: typeof rootRoute }
    '/_authenticated': { preLoaderRoute: typeof AuthenticatedRoute; parentRoute: typeof rootRoute }
    '/_authenticated/chat': { preLoaderRoute: typeof AuthenticatedChatRoute; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/booking': { preLoaderRoute: typeof AuthenticatedBookingRoute; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/dashboard/client': { preLoaderRoute: typeof AuthenticatedDashboardClientRoute; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/dashboard/professional': { preLoaderRoute: typeof AuthenticatedDashboardProfessionalRoute; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/dashboard/admin': { preLoaderRoute: typeof AuthenticatedDashboardAdminRoute; parentRoute: typeof AuthenticatedRoute }
  }
}
